/*
* generated by Xtext
*/
package info.cukes.feature.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CucumberFeatureTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
