/*
 * generated by Xtext
 */
package info.cukes.feature.ui;

import info.cukes.feature.ui.hyperlinking.StepDefinitionHyperlinkDetector;

import org.eclipse.jface.text.hyperlink.IHyperlinkDetector;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CucumberFeatureUiModule extends info.cukes.feature.ui.AbstractCucumberFeatureUiModule {
	public CucumberFeatureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IHyperlinkDetector> bindIHyperlinkDetector() {
		return StepDefinitionHyperlinkDetector.class;
	}
	
}
