<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cucumberFeature"
    nsURI="http://www.cukes.info/feature/CucumberFeature" nsPrefix="cucumberFeature">
  <eClassifiers xsi:type="ecore:EClass" name="Cucumber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" upperBound="-1" eType="#//Feature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fd" eType="#//FeatureDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fb" eType="#//FeatureBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//Background"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ss" upperBound="-1" eType="#//Scenario"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bvd" eType="#//BusinessValueDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rd" eType="#//RoleDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sad" eType="#//SomeActionDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessValueDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SomeActionDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Background">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gb" eType="#//GivenBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wb" eType="#//WhenBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tb" eType="#//ThenBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sd" eType="#//ScenarioDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gb" eType="#//GivenBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wb" eType="#//WhenBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tb" eType="#//ThenBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicScenario" eSuperTypes="#//Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="si" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableScenario" eSuperTypes="#//Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tsi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table_block" eType="#//TableBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ti" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="th" eType="#//TableHeader"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tr" upperBound="-1" eType="#//TableRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GivenBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="given_def" eType="#//GivenDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ab" upperBound="-1" eType="#//AndBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when_def" eType="#//WhenDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ab" upperBound="-1" eType="#//AndBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ti" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then_def" eType="#//ThenDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ab" upperBound="-1" eType="#//AndBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ai" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="and_def" eType="#//AndDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GivenDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhenDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
