/*
* generated by Xtext
*/
package info.cukes.feature.ui.contentassist;

import info.cukes.feature.ui.contentassist.AbstractCucumberFeatureProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CucumberFeatureProposalProvider extends AbstractCucumberFeatureProposalProvider {

}
